GAME_ICON_FILENAME = "game logo image path"
GAME_TITLE = "Snake Voyage"
APPLE_WIDTH = 20
APPLE_HEIGHT = 20
SNAKE_HEIGHT = 20
SNAKE_WIDTH =20
DEFAULT_SNAKE_SPEED = 0.2
GAME_WINDOW_WIDTH = 600
GAME_WINDOW_HEIGHT = 400
FIXED_SNAKE_LENGTH = 6
SURFACE_EXTREME_X_COORDINATE = 565
SURFACE_START_X_COORDINATE = 0
SURFACE_EXTREME_Y_COORDINATE = 470
SURFACE_START_Y_COORDINATE = 35
DEFAULT_SNAKE_X_COORDINATE= 100
DEFAULT_SNAKE_Y_COORDINATE = 100
SCORE_AREA_COLOR = (78, 84, 150)
SCORE_TEXT_COLOR = (190, 195, 250)
SCORE_TEXT_COORDINATES = (0, 0)
DIRECTIONS = {
    "D" :'down',
    "U" : 'up',
    "L" : 'left',
    "R" :'right'
}
DEFAULT_APPLE_X_COORDINATE = 100
DEFAULT_APPLE_Y_COORDINATE = 100
SNAKE_COLOR = (115, 219, 132)
APPLE_COLOR = (220, 53, 69)
SCREEN_BACKGROUND_COLOR = (61, 62, 98)